### ISSUE TITLE
[Question] What is reference paper

### ISSUE THREAD

**Issue by ganyariya** [pkonowrocki/CVRP_ACO#1]
Hello, I'm a student in japan, studying swarm intelligence.

I'd like to study vehicle routing problem, so I'd like to read your repository.

So, would you teach me what paper this repository refers?
Thank you, and sorry for bad english.

**Comment by pkonowrocki** [comment]
Sure @Ganariya, I based my implementation mainly on this paper [Ant Colony Optimization for Capacitated Vehicle Routing Problem by W. F. Tan, L. S. Lee, Z. A. Majid and H. V. Seow](https://thescipub.com/abstract/10.3844/jcssp.2012.846.852).
It uses additional value that describes savings of combining two cities on one tour, as opposed to visiting them on separate tours (parameter gamma).
